import type { IconType } from "react-icons";
import {
  LuActivity,
  LuArchive,
  LuArrowLeftRight,
  LuAward,
  LuBadgePercent,
  LuBanknote,
  LuBell,
  LuBellRing,
  LuBlocks,
  LuBookMarked,
  LuBookOpen,
  LuBookText,
  LuBox,
  LuBoxes,
  LuBriefcase,
  LuBuilding,
  LuBuilding2,
  LuCalculator,
  LuCalendarCheck,
  LuCalendarClock,
  LuCalendarDays,
  LuCalendarOff,
  LuCalendarPlus,
  LuCalendarRange,
  LuCar,
  LuChartColumn,
  LuChartPie,
  LuCheckCheck,
  LuCircleDollarSign,
  LuCirclePlay,
  LuClipboardCheck,
  LuClipboardList,
  LuClock,
  LuCoins,
  LuContact,
  LuCopy,
  LuDatabase,
  LuDatabaseZap,
  LuDiff,
  LuDoorOpen,
  LuFileCheck,
  LuFileDown,
  LuFileInput,
  LuFileMinus,
  LuFileOutput,
  LuFilePen,
  LuFilePenLine,
  LuFilePlus,
  LuFileSpreadsheet,
  LuFileText,
  LuFileUp,
  LuFileX,
  LuFlag,
  LuFlaskConical,
  LuFolderKanban,
  LuFolderOpen,
  LuFolderTree,
  LuFuel,
  LuGauge,
  LuGavel,
  LuGlobe,
  LuHandCoins,
  LuHandshake,
  LuHardHat,
  LuHash,
  LuHeadset,
  LuHourglass,
  LuHouse,
  LuIdCard,
  LuInbox,
  LuKeyRound,
  LuLandmark,
  LuLayers,
  LuLayoutDashboard,
  LuLibrary,
  LuListChecks,
  LuListTodo,
  LuListTree,
  LuLock,
  LuLogIn,
  LuLogOut,
  LuMail,
  LuMailbox,
  LuMapPin,
  LuMapPinned,
  LuMegaphone,
  LuMessageSquare,
  LuMilestone,
  LuNavigation,
  LuNetwork,
  LuPackage,
  LuPackageMinus,
  LuPackagePlus,
  LuPenLine,
  LuPercent,
  LuPhone,
  LuPlane,
  LuPlug,
  LuPresentation,
  LuReceipt,
  LuReceiptText,
  LuRepeat,
  LuRotateCcw,
  LuRoute,
  LuRuler,
  LuScale,
  LuScrollText,
  LuSearch,
  LuSearchX,
  LuSend,
  LuSettings,
  LuShare2,
  LuShieldAlert,
  LuShieldCheck,
  LuShieldHalf,
  LuShoppingCart,
  LuShuffle,
  LuSiren,
  LuSlidersHorizontal,
  LuSparkles,
  LuSplit,
  LuSquareKanban,
  LuStamp,
  LuTableProperties,
  LuTags,
  LuTarget,
  LuTimer,
  LuTractor,
  LuTreePalm,
  LuTrendingDown,
  LuTrendingUp,
  LuTriangleAlert,
  LuTrophy,
  LuTruck,
  LuUndo2,
  LuUnlink,
  LuUser,
  LuUserCheck,
  LuUserCog,
  LuUserPlus,
  LuUserRound,
  LuUserRoundCog,
  LuUsers,
  LuUsersRound,
  LuVault,
  LuWallet,
  LuWarehouse,
  LuWaypoints,
  LuWorkflow,
  LuWrench,
} from "react-icons/lu";

/**
 * The icons the exported app list names (Lucide names, as cicak uses them), mapped to
 * their react-icons components. Generated from `app/data/apps.json`; a name with no
 * match falls back to a plain box.
 */
const ICONS: Record<string, IconType> = {
  Activity: LuActivity,
  Archive: LuArchive,
  ArrowLeftRight: LuArrowLeftRight,
  Award: LuAward,
  BadgePercent: LuBadgePercent,
  Banknote: LuBanknote,
  Bell: LuBell,
  BellRing: LuBellRing,
  Blocks: LuBlocks,
  BookMarked: LuBookMarked,
  BookOpen: LuBookOpen,
  BookText: LuBookText,
  Box: LuBox,
  Boxes: LuBoxes,
  Briefcase: LuBriefcase,
  Building: LuBuilding,
  Building2: LuBuilding2,
  Calculator: LuCalculator,
  CalendarCheck: LuCalendarCheck,
  CalendarClock: LuCalendarClock,
  CalendarDays: LuCalendarDays,
  CalendarOff: LuCalendarOff,
  CalendarPlus: LuCalendarPlus,
  CalendarRange: LuCalendarRange,
  Car: LuCar,
  ChartColumn: LuChartColumn,
  ChartPie: LuChartPie,
  CheckCheck: LuCheckCheck,
  CircleDollarSign: LuCircleDollarSign,
  CirclePlay: LuCirclePlay,
  ClipboardCheck: LuClipboardCheck,
  ClipboardList: LuClipboardList,
  Clock: LuClock,
  Coins: LuCoins,
  Contact: LuContact,
  Copy: LuCopy,
  Database: LuDatabase,
  DatabaseZap: LuDatabaseZap,
  Diff: LuDiff,
  DoorOpen: LuDoorOpen,
  FileCheck: LuFileCheck,
  FileDown: LuFileDown,
  FileInput: LuFileInput,
  FileMinus: LuFileMinus,
  FileOutput: LuFileOutput,
  FilePen: LuFilePen,
  FilePenLine: LuFilePenLine,
  FilePlus: LuFilePlus,
  FileSpreadsheet: LuFileSpreadsheet,
  FileText: LuFileText,
  FileUp: LuFileUp,
  FileX: LuFileX,
  Flag: LuFlag,
  FlaskConical: LuFlaskConical,
  FolderKanban: LuFolderKanban,
  FolderOpen: LuFolderOpen,
  FolderTree: LuFolderTree,
  Fuel: LuFuel,
  Gauge: LuGauge,
  Gavel: LuGavel,
  Globe: LuGlobe,
  HandCoins: LuHandCoins,
  Handshake: LuHandshake,
  HardHat: LuHardHat,
  Hash: LuHash,
  Headset: LuHeadset,
  Hourglass: LuHourglass,
  House: LuHouse,
  IdCard: LuIdCard,
  Inbox: LuInbox,
  KeyRound: LuKeyRound,
  Landmark: LuLandmark,
  Layers: LuLayers,
  LayoutDashboard: LuLayoutDashboard,
  Library: LuLibrary,
  ListChecks: LuListChecks,
  ListTodo: LuListTodo,
  ListTree: LuListTree,
  Lock: LuLock,
  LogIn: LuLogIn,
  LogOut: LuLogOut,
  Mail: LuMail,
  Mailbox: LuMailbox,
  MapPin: LuMapPin,
  MapPinned: LuMapPinned,
  Megaphone: LuMegaphone,
  MessageSquare: LuMessageSquare,
  Milestone: LuMilestone,
  Navigation: LuNavigation,
  Network: LuNetwork,
  Package: LuPackage,
  PackageMinus: LuPackageMinus,
  PackagePlus: LuPackagePlus,
  PenLine: LuPenLine,
  Percent: LuPercent,
  Phone: LuPhone,
  Plane: LuPlane,
  Plug: LuPlug,
  Presentation: LuPresentation,
  Receipt: LuReceipt,
  ReceiptText: LuReceiptText,
  Repeat: LuRepeat,
  RotateCcw: LuRotateCcw,
  Route: LuRoute,
  Ruler: LuRuler,
  Scale: LuScale,
  ScrollText: LuScrollText,
  Search: LuSearch,
  SearchX: LuSearchX,
  Send: LuSend,
  Settings: LuSettings,
  Share2: LuShare2,
  ShieldAlert: LuShieldAlert,
  ShieldCheck: LuShieldCheck,
  ShieldHalf: LuShieldHalf,
  ShoppingCart: LuShoppingCart,
  Shuffle: LuShuffle,
  Siren: LuSiren,
  SlidersHorizontal: LuSlidersHorizontal,
  Sparkles: LuSparkles,
  Split: LuSplit,
  SquareKanban: LuSquareKanban,
  Stamp: LuStamp,
  TableProperties: LuTableProperties,
  Tags: LuTags,
  Target: LuTarget,
  Timer: LuTimer,
  Tractor: LuTractor,
  TreePalm: LuTreePalm,
  TrendingDown: LuTrendingDown,
  TrendingUp: LuTrendingUp,
  TriangleAlert: LuTriangleAlert,
  Trophy: LuTrophy,
  Truck: LuTruck,
  Undo2: LuUndo2,
  Unlink: LuUnlink,
  User: LuUser,
  UserCheck: LuUserCheck,
  UserCog: LuUserCog,
  UserPlus: LuUserPlus,
  UserRound: LuUserRound,
  UserRoundCog: LuUserRoundCog,
  Users: LuUsers,
  UsersRound: LuUsersRound,
  Vault: LuVault,
  Wallet: LuWallet,
  Warehouse: LuWarehouse,
  Waypoints: LuWaypoints,
  Workflow: LuWorkflow,
  Wrench: LuWrench,
};

export const iconFor = (name: string | null | undefined): IconType => (name && ICONS[name]) || LuBox;
